type: spec.insomnia.rest/5.0
schema_version: "5.1"
name: New-Insomnia
meta:
  id: wrk_b552b945d1f540508ce4d6a4f9543709
  created: 1770024780510
  modified: 1770024780510
  description: ""
cookieJar:
  name: Default Jar
  meta:
    id: jar_2df4b5207da55ffdd8c42942c8717920895dd3b4
    created: 1770024780538
    modified: 1770024780538
environments:
  name: Base Environment
  meta:
    id: env_2df4b5207da55ffdd8c42942c8717920895dd3b4
    created: 1770024780537
    modified: 1770024780537
    isPrivate: false
spec:
  contents:
    openapi: 3.0.0
    info:
      title: Open Api Specification
      version: 1.0.0
      description: This tells about the api.
      contact:
        name: naman
        email: naman@support.com
    servers:
      - url: http://httpbin.org:80
        description: This is the actual backend server.
    tags:
      - name: kong-api
        description: This is the  kong api tag.
      - name: health-api
        description: This is the health api tag.
    paths:
      /kong-routes:
        get:
          summary: This is the paths that direct to the service.
          description: This shows the path of the service.
          operationId: abcd
          tags:
            - kong-api
          responses:
            "200":
              description: ok
      /health:
        get:
          summary: This is the route for the heath service.
          description: This shows the path of the health service
          operationId: efgh
          tags:
            - health-api
          responses:
            "200":
              description: ok
  meta:
    id: spc_59b106ecaf3740eeb6ed058879b26cdf
    created: 1770024780535
    modified: 1770032422905
